# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='beat_event.proto',
  package='',
  serialized_pb='\n\x10\x62\x65\x61t_event.proto\"`\n\tBeatEvent\x12\x1d\n\x04type\x18\x01 \x02(\x0e\x32\t.BeatType:\x04\x42\x45\x41T\x12\x0c\n\x04\x62\x65\x61t\x18\x02 \x01(\x05\x12\x10\n\x08sub_beat\x18\x03 \x01(\x05\x12\x14\n\x0cscene_number\x18\x04 \x01(\x05*4\n\x08\x42\x65\x61tType\x12\x08\n\x04\x42\x45\x41T\x10\x00\x12\x0c\n\x08SUB_BEAT\x10\x01\x12\x10\n\x0c\x43HANGE_SCENE\x10\x02')

_BEATTYPE = descriptor.EnumDescriptor(
  name='BeatType',
  full_name='BeatType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='BEAT', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SUB_BEAT', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CHANGE_SCENE', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=118,
  serialized_end=170,
)


BEAT = 0
SUB_BEAT = 1
CHANGE_SCENE = 2



_BEATEVENT = descriptor.Descriptor(
  name='BeatEvent',
  full_name='BeatEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='BeatEvent.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='beat', full_name='BeatEvent.beat', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='sub_beat', full_name='BeatEvent.sub_beat', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='scene_number', full_name='BeatEvent.scene_number', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=20,
  serialized_end=116,
)

_BEATEVENT.fields_by_name['type'].enum_type = _BEATTYPE
DESCRIPTOR.message_types_by_name['BeatEvent'] = _BEATEVENT

class BeatEvent(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BEATEVENT
  
  # @@protoc_insertion_point(class_scope:BeatEvent)

# @@protoc_insertion_point(module_scope)
